name: Release

on:
  push:
    tags: ["v*"]
  pull_request: # tentative setting (will be removed)
    types: [opened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: DOCKER_BUILDKIT=1 IMAGE_PREFIX=ghcr.io/${{ github.actor }} make build-image-cli
    - run: RELEASE_TAG=${GITHUB_REF##*/} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make release-assets


