name: Release

on:
  push:
    tags: ["v*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
    - run: curl -sLo- https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar -xjC "$GOPATH/bin" --strip-components 3 -f-
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: DOCKER_BUILDKIT=1 IMAGE_PREFIX=ghcr.io/${{ github.actor }} make build-image-cli
    - run: RELEASE_TAG=${GITHUB_REF##*/} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make release-assets


